services:
  eterny-iq:
    build: .
    container_name: eterny-iq
    ports:
      - 8880:8880
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    environment:
      - TZ=Europe/Bratislava
    volumes:
      - ./data:/code/data
    command: >
      gunicorn
      --worker-class uvicorn.workers.UvicornWorker
      --workers ${NEURAL_API_WORKERS:-1}
      --bind 0.0.0.0:8880
      backend.main:app
    healthcheck:
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  data_volume: {}
  cert_volume: {}
